#pragma checksum "..\..\..\..\..\..\..\..\NerdSharp_UberNet\Science\Comp_Sci\StudioComponents\SideComponents\Desktop.xaml" "{406ea660-64cf-4c82-b6f0-42d48172a799}" "2ED3CE1DE4C8B8E5678A9B3D6391624A"
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17626
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Microsoft.Windows.Controls;
using System;
using System.Diagnostics;
using System.Windows;
using System.Windows.Automation;
using System.Windows.Controls;
using System.Windows.Controls.Primitives;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Forms.Integration;
using System.Windows.Ink;
using System.Windows.Input;
using System.Windows.Markup;
using System.Windows.Media;
using System.Windows.Media.Animation;
using System.Windows.Media.Effects;
using System.Windows.Media.Imaging;
using System.Windows.Media.Media3D;
using System.Windows.Media.TextFormatting;
using System.Windows.Navigation;
using System.Windows.Shapes;
using System.Windows.Shell;


namespace NerdSharp.Net_Studio.NerdSharp_UberNet.Science.Comp_Sci.StudioComponents.SideComponents {
    
    
    /// <summary>
    /// Desktop
    /// </summary>
    public partial class Desktop : System.Windows.Controls.UserControl, System.Windows.Markup.IComponentConnector {
        
        
        #line 10 "..\..\..\..\..\..\..\..\NerdSharp_UberNet\Science\Comp_Sci\StudioComponents\SideComponents\Desktop.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Grid desktopGrid;
        
        #line default
        #line hidden
        
        
        #line 14 "..\..\..\..\..\..\..\..\NerdSharp_UberNet\Science\Comp_Sci\StudioComponents\SideComponents\Desktop.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Shapes.Polygon leftWallPolyGon;
        
        #line default
        #line hidden
        
        
        #line 18 "..\..\..\..\..\..\..\..\NerdSharp_UberNet\Science\Comp_Sci\StudioComponents\SideComponents\Desktop.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Grid leftWallBgGrid;
        
        #line default
        #line hidden
        
        
        #line 19 "..\..\..\..\..\..\..\..\NerdSharp_UberNet\Science\Comp_Sci\StudioComponents\SideComponents\Desktop.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Image leftWallBgImg;
        
        #line default
        #line hidden
        
        
        #line 33 "..\..\..\..\..\..\..\..\NerdSharp_UberNet\Science\Comp_Sci\StudioComponents\SideComponents\Desktop.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Shapes.Polygon floorPolygon;
        
        #line default
        #line hidden
        
        
        #line 37 "..\..\..\..\..\..\..\..\NerdSharp_UberNet\Science\Comp_Sci\StudioComponents\SideComponents\Desktop.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Label changeImageMenuItemLable;
        
        #line default
        #line hidden
        
        
        #line 43 "..\..\..\..\..\..\..\..\NerdSharp_UberNet\Science\Comp_Sci\StudioComponents\SideComponents\Desktop.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.ComboBoxItem tilePictureCmBxItem;
        
        #line default
        #line hidden
        
        
        #line 44 "..\..\..\..\..\..\..\..\NerdSharp_UberNet\Science\Comp_Sci\StudioComponents\SideComponents\Desktop.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Label tileTextBlock;
        
        #line default
        #line hidden
        
        
        #line 51 "..\..\..\..\..\..\..\..\NerdSharp_UberNet\Science\Comp_Sci\StudioComponents\SideComponents\Desktop.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Media.VisualBrush floorBgVisBrush;
        
        #line default
        #line hidden
        
        
        #line 53 "..\..\..\..\..\..\..\..\NerdSharp_UberNet\Science\Comp_Sci\StudioComponents\SideComponents\Desktop.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Grid floorBgGrid;
        
        #line default
        #line hidden
        
        
        #line 54 "..\..\..\..\..\..\..\..\NerdSharp_UberNet\Science\Comp_Sci\StudioComponents\SideComponents\Desktop.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Image bgImg;
        
        #line default
        #line hidden
        
        
        #line 65 "..\..\..\..\..\..\..\..\NerdSharp_UberNet\Science\Comp_Sci\StudioComponents\SideComponents\Desktop.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button browser;
        
        #line default
        #line hidden
        
        private bool _contentLoaded;
        
        /// <summary>
        /// InitializeComponent
        /// </summary>
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "4.0.0.0")]
        public void InitializeComponent() {
            if (_contentLoaded) {
                return;
            }
            _contentLoaded = true;
            System.Uri resourceLocater = new System.Uri("/NerdSharp.Net_Studio;component/nerdsharp_ubernet/science/comp_sci/studiocomponen" +
                    "ts/sidecomponents/desktop.xaml", System.UriKind.Relative);
            
            #line 1 "..\..\..\..\..\..\..\..\NerdSharp_UberNet\Science\Comp_Sci\StudioComponents\SideComponents\Desktop.xaml"
            System.Windows.Application.LoadComponent(this, resourceLocater);
            
            #line default
            #line hidden
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "4.0.0.0")]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Design", "CA1033:InterfaceMethodsShouldBeCallableByChildTypes")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Maintainability", "CA1502:AvoidExcessiveComplexity")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1800:DoNotCastUnnecessarily")]
        void System.Windows.Markup.IComponentConnector.Connect(int connectionId, object target) {
            switch (connectionId)
            {
            case 1:
            this.desktopGrid = ((System.Windows.Controls.Grid)(target));
            
            #line 10 "..\..\..\..\..\..\..\..\NerdSharp_UberNet\Science\Comp_Sci\StudioComponents\SideComponents\Desktop.xaml"
            this.desktopGrid.SizeChanged += new System.Windows.SizeChangedEventHandler(this.desktopGrid_SizeChanged);
            
            #line default
            #line hidden
            return;
            case 2:
            this.leftWallPolyGon = ((System.Windows.Shapes.Polygon)(target));
            return;
            case 3:
            this.leftWallBgGrid = ((System.Windows.Controls.Grid)(target));
            return;
            case 4:
            this.leftWallBgImg = ((System.Windows.Controls.Image)(target));
            return;
            case 5:
            this.floorPolygon = ((System.Windows.Shapes.Polygon)(target));
            
            #line 33 "..\..\..\..\..\..\..\..\NerdSharp_UberNet\Science\Comp_Sci\StudioComponents\SideComponents\Desktop.xaml"
            this.floorPolygon.Loaded += new System.Windows.RoutedEventHandler(this.floorPolygon_Loaded);
            
            #line default
            #line hidden
            return;
            case 6:
            this.changeImageMenuItemLable = ((System.Windows.Controls.Label)(target));
            
            #line 38 "..\..\..\..\..\..\..\..\NerdSharp_UberNet\Science\Comp_Sci\StudioComponents\SideComponents\Desktop.xaml"
            this.changeImageMenuItemLable.MouseDown += new System.Windows.Input.MouseButtonEventHandler(this.changeImageMenuItemLable_MouseDown);
            
            #line default
            #line hidden
            return;
            case 7:
            this.tilePictureCmBxItem = ((System.Windows.Controls.ComboBoxItem)(target));
            
            #line 43 "..\..\..\..\..\..\..\..\NerdSharp_UberNet\Science\Comp_Sci\StudioComponents\SideComponents\Desktop.xaml"
            this.tilePictureCmBxItem.Selected += new System.Windows.RoutedEventHandler(this.tilePictureCmBxItem_Selected);
            
            #line default
            #line hidden
            return;
            case 8:
            this.tileTextBlock = ((System.Windows.Controls.Label)(target));
            
            #line 44 "..\..\..\..\..\..\..\..\NerdSharp_UberNet\Science\Comp_Sci\StudioComponents\SideComponents\Desktop.xaml"
            this.tileTextBlock.MouseLeftButtonDown += new System.Windows.Input.MouseButtonEventHandler(this.tileTextBlock_MouseLeftButtonDown);
            
            #line default
            #line hidden
            return;
            case 9:
            this.floorBgVisBrush = ((System.Windows.Media.VisualBrush)(target));
            return;
            case 10:
            this.floorBgGrid = ((System.Windows.Controls.Grid)(target));
            return;
            case 11:
            this.bgImg = ((System.Windows.Controls.Image)(target));
            return;
            case 12:
            this.browser = ((System.Windows.Controls.Button)(target));
            
            #line 65 "..\..\..\..\..\..\..\..\NerdSharp_UberNet\Science\Comp_Sci\StudioComponents\SideComponents\Desktop.xaml"
            this.browser.Click += new System.Windows.RoutedEventHandler(this.browser_Click);
            
            #line default
            #line hidden
            return;
            }
            this._contentLoaded = true;
        }
    }
}

