// Implementation file for parser generated by fsyacc
module IsblParser
#nowarn "64";; // turn off warnings that type variables used in production annotations are instantiated to concrete type
open Microsoft.FSharp.Text.Lexing
open Microsoft.FSharp.Text.Parsing.ParseHelpers
# 1 "C:\Projects\IsblInterpreter\IsblInterpreter\\IsblParser.fsy"

open IsblAst

# 10 "C:\Projects\IsblInterpreter\IsblInterpreter\IsblParser.fs"
// This type is the type of tokens accepted by the parser
type token = 
  | WHILE
  | DO
  | BEGIN
  | END
  | PRINT
  | SEMI
  | ASSIGN
  | EOF
  | PLUS
  | MINUS
  | TIMES
  | LPAREN
  | RPAREN
  | IF
  | ENDIF
  | ELSE
  | INT of (int)
  | ID of (string)
// This type is used to give symbolic names to token indexes, useful for error messages
type tokenId = 
    | TOKEN_WHILE
    | TOKEN_DO
    | TOKEN_BEGIN
    | TOKEN_END
    | TOKEN_PRINT
    | TOKEN_SEMI
    | TOKEN_ASSIGN
    | TOKEN_EOF
    | TOKEN_PLUS
    | TOKEN_MINUS
    | TOKEN_TIMES
    | TOKEN_LPAREN
    | TOKEN_RPAREN
    | TOKEN_IF
    | TOKEN_ENDIF
    | TOKEN_ELSE
    | TOKEN_INT
    | TOKEN_ID
    | TOKEN_end_of_input
    | TOKEN_error
// This type is used to give symbolic names to token indexes, useful for error messages
type nonTerminalId = 
    | NONTERM__startstart
    | NONTERM_start
    | NONTERM_Prog
    | NONTERM_Expr
    | NONTERM_Stmt
    | NONTERM_StmtList

// This function maps tokens to integers indexes
let tagOfToken (t:token) = 
  match t with
  | WHILE  -> 0 
  | DO  -> 1 
  | BEGIN  -> 2 
  | END  -> 3 
  | PRINT  -> 4 
  | SEMI  -> 5 
  | ASSIGN  -> 6 
  | EOF  -> 7 
  | PLUS  -> 8 
  | MINUS  -> 9 
  | TIMES  -> 10 
  | LPAREN  -> 11 
  | RPAREN  -> 12 
  | IF  -> 13 
  | ENDIF  -> 14 
  | ELSE  -> 15 
  | INT _ -> 16 
  | ID _ -> 17 

// This function maps integers indexes to symbolic token ids
let tokenTagToTokenId (tokenIdx:int) = 
  match tokenIdx with
  | 0 -> TOKEN_WHILE 
  | 1 -> TOKEN_DO 
  | 2 -> TOKEN_BEGIN 
  | 3 -> TOKEN_END 
  | 4 -> TOKEN_PRINT 
  | 5 -> TOKEN_SEMI 
  | 6 -> TOKEN_ASSIGN 
  | 7 -> TOKEN_EOF 
  | 8 -> TOKEN_PLUS 
  | 9 -> TOKEN_MINUS 
  | 10 -> TOKEN_TIMES 
  | 11 -> TOKEN_LPAREN 
  | 12 -> TOKEN_RPAREN 
  | 13 -> TOKEN_IF 
  | 14 -> TOKEN_ENDIF 
  | 15 -> TOKEN_ELSE 
  | 16 -> TOKEN_INT 
  | 17 -> TOKEN_ID 
  | 20 -> TOKEN_end_of_input
  | 18 -> TOKEN_error
  | _ -> failwith "tokenTagToTokenId: bad token"

/// This function maps production indexes returned in syntax errors to strings representing the non terminal that would be produced by that production
let prodIdxToNonTerminal (prodIdx:int) = 
  match prodIdx with
    | 0 -> NONTERM__startstart 
    | 1 -> NONTERM_start 
    | 2 -> NONTERM_Prog 
    | 3 -> NONTERM_Expr 
    | 4 -> NONTERM_Expr 
    | 5 -> NONTERM_Expr 
    | 6 -> NONTERM_Expr 
    | 7 -> NONTERM_Expr 
    | 8 -> NONTERM_Stmt 
    | 9 -> NONTERM_Stmt 
    | 10 -> NONTERM_Stmt 
    | 11 -> NONTERM_Stmt 
    | 12 -> NONTERM_Stmt 
    | 13 -> NONTERM_Stmt 
    | 14 -> NONTERM_StmtList 
    | 15 -> NONTERM_StmtList 
    | _ -> failwith "prodIdxToNonTerminal: bad production index"

let _fsyacc_endOfInputTag = 20 
let _fsyacc_tagOfErrorTerminal = 18

// This function gets the name of a token as a string
let token_to_string (t:token) = 
  match t with 
  | WHILE  -> "WHILE" 
  | DO  -> "DO" 
  | BEGIN  -> "BEGIN" 
  | END  -> "END" 
  | PRINT  -> "PRINT" 
  | SEMI  -> "SEMI" 
  | ASSIGN  -> "ASSIGN" 
  | EOF  -> "EOF" 
  | PLUS  -> "PLUS" 
  | MINUS  -> "MINUS" 
  | TIMES  -> "TIMES" 
  | LPAREN  -> "LPAREN" 
  | RPAREN  -> "RPAREN" 
  | IF  -> "IF" 
  | ENDIF  -> "ENDIF" 
  | ELSE  -> "ELSE" 
  | INT _ -> "INT" 
  | ID _ -> "ID" 

// This function gets the data carried by a token as an object
let _fsyacc_dataOfToken (t:token) = 
  match t with 
  | WHILE  -> (null : System.Object) 
  | DO  -> (null : System.Object) 
  | BEGIN  -> (null : System.Object) 
  | END  -> (null : System.Object) 
  | PRINT  -> (null : System.Object) 
  | SEMI  -> (null : System.Object) 
  | ASSIGN  -> (null : System.Object) 
  | EOF  -> (null : System.Object) 
  | PLUS  -> (null : System.Object) 
  | MINUS  -> (null : System.Object) 
  | TIMES  -> (null : System.Object) 
  | LPAREN  -> (null : System.Object) 
  | RPAREN  -> (null : System.Object) 
  | IF  -> (null : System.Object) 
  | ENDIF  -> (null : System.Object) 
  | ELSE  -> (null : System.Object) 
  | INT _fsyacc_x -> Microsoft.FSharp.Core.Operators.box _fsyacc_x 
  | ID _fsyacc_x -> Microsoft.FSharp.Core.Operators.box _fsyacc_x 
let _fsyacc_gotos = [| 0us; 65535us; 1us; 65535us; 0us; 1us; 1us; 65535us; 0us; 2us; 7us; 65535us; 13us; 6us; 14us; 7us; 15us; 8us; 18us; 9us; 19us; 10us; 25us; 11us; 31us; 12us; 6us; 65535us; 0us; 32us; 11us; 32us; 20us; 21us; 22us; 32us; 28us; 32us; 33us; 34us; 4us; 65535us; 0us; 3us; 11us; 26us; 22us; 23us; 28us; 29us; |]
let _fsyacc_sparseGotoTableRowOffsets = [|0us; 1us; 3us; 5us; 13us; 20us; |]
let _fsyacc_stateToProdIdxsTableElements = [| 1us; 0us; 1us; 0us; 1us; 1us; 2us; 2us; 15us; 1us; 3us; 1us; 4us; 3us; 5us; 5us; 6us; 3us; 5us; 6us; 6us; 3us; 5us; 6us; 7us; 3us; 5us; 6us; 8us; 3us; 5us; 6us; 9us; 4us; 5us; 6us; 11us; 12us; 3us; 5us; 6us; 13us; 1us; 5us; 1us; 6us; 1us; 7us; 1us; 7us; 1us; 8us; 1us; 8us; 1us; 9us; 1us; 9us; 1us; 9us; 1us; 10us; 2us; 10us; 15us; 1us; 10us; 2us; 11us; 12us; 3us; 11us; 12us; 15us; 1us; 11us; 1us; 12us; 2us; 12us; 15us; 1us; 12us; 1us; 13us; 1us; 14us; 1us; 15us; 1us; 15us; |]
let _fsyacc_stateToProdIdxsTableRowOffsets = [|0us; 2us; 4us; 6us; 9us; 11us; 13us; 17us; 21us; 25us; 29us; 33us; 38us; 42us; 44us; 46us; 48us; 50us; 52us; 54us; 56us; 58us; 60us; 62us; 65us; 67us; 70us; 74us; 76us; 78us; 81us; 83us; 85us; 87us; 89us; |]
let _fsyacc_action_rows = 35
let _fsyacc_actionTableElements = [|5us; 32768us; 0us; 19us; 2us; 22us; 4us; 31us; 13us; 25us; 17us; 17us; 0us; 49152us; 0us; 16385us; 1us; 16386us; 5us; 33us; 0us; 16387us; 0us; 16388us; 0us; 16389us; 0us; 16390us; 3us; 32768us; 8us; 13us; 9us; 14us; 12us; 16us; 2us; 16392us; 8us; 13us; 9us; 14us; 3us; 32768us; 1us; 20us; 8us; 13us; 9us; 14us; 7us; 32768us; 0us; 19us; 2us; 22us; 4us; 31us; 8us; 13us; 9us; 14us; 13us; 25us; 17us; 17us; 2us; 16397us; 8us; 13us; 9us; 14us; 3us; 32768us; 11us; 15us; 16us; 5us; 17us; 4us; 3us; 32768us; 11us; 15us; 16us; 5us; 17us; 4us; 3us; 32768us; 11us; 15us; 16us; 5us; 17us; 4us; 0us; 16391us; 1us; 32768us; 6us; 18us; 3us; 32768us; 11us; 15us; 16us; 5us; 17us; 4us; 3us; 32768us; 11us; 15us; 16us; 5us; 17us; 4us; 5us; 32768us; 0us; 19us; 2us; 22us; 4us; 31us; 13us; 25us; 17us; 17us; 0us; 16393us; 5us; 32768us; 0us; 19us; 2us; 22us; 4us; 31us; 13us; 25us; 17us; 17us; 2us; 32768us; 3us; 24us; 5us; 33us; 0us; 16394us; 3us; 32768us; 11us; 15us; 16us; 5us; 17us; 4us; 3us; 32768us; 5us; 33us; 14us; 27us; 15us; 28us; 0us; 16395us; 5us; 32768us; 0us; 19us; 2us; 22us; 4us; 31us; 13us; 25us; 17us; 17us; 2us; 32768us; 5us; 33us; 14us; 30us; 0us; 16396us; 3us; 32768us; 11us; 15us; 16us; 5us; 17us; 4us; 0us; 16398us; 5us; 32768us; 0us; 19us; 2us; 22us; 4us; 31us; 13us; 25us; 17us; 17us; 0us; 16399us; |]
let _fsyacc_actionTableRowOffsets = [|0us; 6us; 7us; 8us; 10us; 11us; 12us; 13us; 14us; 18us; 21us; 25us; 33us; 36us; 40us; 44us; 48us; 49us; 51us; 55us; 59us; 65us; 66us; 72us; 75us; 76us; 80us; 84us; 85us; 91us; 94us; 95us; 99us; 100us; 106us; |]
let _fsyacc_reductionSymbolCounts = [|1us; 1us; 1us; 1us; 1us; 3us; 3us; 3us; 3us; 4us; 3us; 4us; 6us; 2us; 1us; 3us; |]
let _fsyacc_productionToNonTerminalTable = [|0us; 1us; 2us; 3us; 3us; 3us; 3us; 3us; 4us; 4us; 4us; 4us; 4us; 4us; 5us; 5us; |]
let _fsyacc_immediateActions = [|65535us; 49152us; 16385us; 65535us; 16387us; 16388us; 65535us; 65535us; 65535us; 65535us; 65535us; 65535us; 65535us; 65535us; 65535us; 65535us; 16391us; 65535us; 65535us; 65535us; 65535us; 16393us; 65535us; 65535us; 16394us; 65535us; 65535us; 16395us; 65535us; 65535us; 16396us; 65535us; 16398us; 65535us; 16399us; |]
let _fsyacc_reductions ()  =    [| 
# 187 "C:\Projects\IsblInterpreter\IsblInterpreter\IsblParser.fs"
        (fun (parseState : Microsoft.FSharp.Text.Parsing.IParseState) ->
            let _1 = (let data = parseState.GetInput(1) in (Microsoft.FSharp.Core.Operators.unbox data : prog)) in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
                      raise (Microsoft.FSharp.Text.Parsing.Accept(Microsoft.FSharp.Core.Operators.box _1))
                   )
                 : '_startstart));
# 196 "C:\Projects\IsblInterpreter\IsblInterpreter\IsblParser.fs"
        (fun (parseState : Microsoft.FSharp.Text.Parsing.IParseState) ->
            let _1 = (let data = parseState.GetInput(1) in (Microsoft.FSharp.Core.Operators.unbox data : 'Prog)) in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 24 "C:\Projects\IsblInterpreter\IsblInterpreter\\IsblParser.fsy"
                                                     _1 
                   )
# 24 "C:\Projects\IsblInterpreter\IsblInterpreter\\IsblParser.fsy"
                 : prog));
# 207 "C:\Projects\IsblInterpreter\IsblInterpreter\IsblParser.fs"
        (fun (parseState : Microsoft.FSharp.Text.Parsing.IParseState) ->
            let _1 = (let data = parseState.GetInput(1) in (Microsoft.FSharp.Core.Operators.unbox data : 'StmtList)) in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 26 "C:\Projects\IsblInterpreter\IsblInterpreter\\IsblParser.fsy"
                                                     Prog (List.rev _1) 
                   )
# 26 "C:\Projects\IsblInterpreter\IsblInterpreter\\IsblParser.fsy"
                 : 'Prog));
# 218 "C:\Projects\IsblInterpreter\IsblInterpreter\IsblParser.fs"
        (fun (parseState : Microsoft.FSharp.Text.Parsing.IParseState) ->
            let _1 = (let data = parseState.GetInput(1) in (Microsoft.FSharp.Core.Operators.unbox data : string)) in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 28 "C:\Projects\IsblInterpreter\IsblInterpreter\\IsblParser.fsy"
                                                     Val _1 
                   )
# 28 "C:\Projects\IsblInterpreter\IsblInterpreter\\IsblParser.fsy"
                 : 'Expr));
# 229 "C:\Projects\IsblInterpreter\IsblInterpreter\IsblParser.fs"
        (fun (parseState : Microsoft.FSharp.Text.Parsing.IParseState) ->
            let _1 = (let data = parseState.GetInput(1) in (Microsoft.FSharp.Core.Operators.unbox data : int)) in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 29 "C:\Projects\IsblInterpreter\IsblInterpreter\\IsblParser.fsy"
                                                     Int _1 
                   )
# 29 "C:\Projects\IsblInterpreter\IsblInterpreter\\IsblParser.fsy"
                 : 'Expr));
# 240 "C:\Projects\IsblInterpreter\IsblInterpreter\IsblParser.fs"
        (fun (parseState : Microsoft.FSharp.Text.Parsing.IParseState) ->
            let _1 = (let data = parseState.GetInput(1) in (Microsoft.FSharp.Core.Operators.unbox data : 'Expr)) in
            let _3 = (let data = parseState.GetInput(3) in (Microsoft.FSharp.Core.Operators.unbox data : 'Expr)) in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 30 "C:\Projects\IsblInterpreter\IsblInterpreter\\IsblParser.fsy"
                                                     Plus (_1, _3) 
                   )
# 30 "C:\Projects\IsblInterpreter\IsblInterpreter\\IsblParser.fsy"
                 : 'Expr));
# 252 "C:\Projects\IsblInterpreter\IsblInterpreter\IsblParser.fs"
        (fun (parseState : Microsoft.FSharp.Text.Parsing.IParseState) ->
            let _1 = (let data = parseState.GetInput(1) in (Microsoft.FSharp.Core.Operators.unbox data : 'Expr)) in
            let _3 = (let data = parseState.GetInput(3) in (Microsoft.FSharp.Core.Operators.unbox data : 'Expr)) in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 31 "C:\Projects\IsblInterpreter\IsblInterpreter\\IsblParser.fsy"
                                                     Minus (_1, _3) 
                   )
# 31 "C:\Projects\IsblInterpreter\IsblInterpreter\\IsblParser.fsy"
                 : 'Expr));
# 264 "C:\Projects\IsblInterpreter\IsblInterpreter\IsblParser.fs"
        (fun (parseState : Microsoft.FSharp.Text.Parsing.IParseState) ->
            let _2 = (let data = parseState.GetInput(2) in (Microsoft.FSharp.Core.Operators.unbox data : 'Expr)) in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 32 "C:\Projects\IsblInterpreter\IsblInterpreter\\IsblParser.fsy"
                                                     _2 
                   )
# 32 "C:\Projects\IsblInterpreter\IsblInterpreter\\IsblParser.fsy"
                 : 'Expr));
# 275 "C:\Projects\IsblInterpreter\IsblInterpreter\IsblParser.fs"
        (fun (parseState : Microsoft.FSharp.Text.Parsing.IParseState) ->
            let _1 = (let data = parseState.GetInput(1) in (Microsoft.FSharp.Core.Operators.unbox data : string)) in
            let _3 = (let data = parseState.GetInput(3) in (Microsoft.FSharp.Core.Operators.unbox data : 'Expr)) in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 34 "C:\Projects\IsblInterpreter\IsblInterpreter\\IsblParser.fsy"
                                                                  Assign (_1, _3) 
                   )
# 34 "C:\Projects\IsblInterpreter\IsblInterpreter\\IsblParser.fsy"
                 : 'Stmt));
# 287 "C:\Projects\IsblInterpreter\IsblInterpreter\IsblParser.fs"
        (fun (parseState : Microsoft.FSharp.Text.Parsing.IParseState) ->
            let _2 = (let data = parseState.GetInput(2) in (Microsoft.FSharp.Core.Operators.unbox data : 'Expr)) in
            let _4 = (let data = parseState.GetInput(4) in (Microsoft.FSharp.Core.Operators.unbox data : 'Stmt)) in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 35 "C:\Projects\IsblInterpreter\IsblInterpreter\\IsblParser.fsy"
                                                                  While (_2, _4) 
                   )
# 35 "C:\Projects\IsblInterpreter\IsblInterpreter\\IsblParser.fsy"
                 : 'Stmt));
# 299 "C:\Projects\IsblInterpreter\IsblInterpreter\IsblParser.fs"
        (fun (parseState : Microsoft.FSharp.Text.Parsing.IParseState) ->
            let _2 = (let data = parseState.GetInput(2) in (Microsoft.FSharp.Core.Operators.unbox data : 'StmtList)) in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 36 "C:\Projects\IsblInterpreter\IsblInterpreter\\IsblParser.fsy"
                                                                  Seq (List.rev _2) 
                   )
# 36 "C:\Projects\IsblInterpreter\IsblInterpreter\\IsblParser.fsy"
                 : 'Stmt));
# 310 "C:\Projects\IsblInterpreter\IsblInterpreter\IsblParser.fs"
        (fun (parseState : Microsoft.FSharp.Text.Parsing.IParseState) ->
            let _2 = (let data = parseState.GetInput(2) in (Microsoft.FSharp.Core.Operators.unbox data : 'Expr)) in
            let _3 = (let data = parseState.GetInput(3) in (Microsoft.FSharp.Core.Operators.unbox data : 'StmtList)) in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 37 "C:\Projects\IsblInterpreter\IsblInterpreter\\IsblParser.fsy"
                                                                  IfThen (_2, List.rev _3) 
                   )
# 37 "C:\Projects\IsblInterpreter\IsblInterpreter\\IsblParser.fsy"
                 : 'Stmt));
# 322 "C:\Projects\IsblInterpreter\IsblInterpreter\IsblParser.fs"
        (fun (parseState : Microsoft.FSharp.Text.Parsing.IParseState) ->
            let _2 = (let data = parseState.GetInput(2) in (Microsoft.FSharp.Core.Operators.unbox data : 'Expr)) in
            let _3 = (let data = parseState.GetInput(3) in (Microsoft.FSharp.Core.Operators.unbox data : 'StmtList)) in
            let _5 = (let data = parseState.GetInput(5) in (Microsoft.FSharp.Core.Operators.unbox data : 'StmtList)) in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 38 "C:\Projects\IsblInterpreter\IsblInterpreter\\IsblParser.fsy"
                                                                  IfThenElse (_2, List.rev _3, List.rev _5) 
                   )
# 38 "C:\Projects\IsblInterpreter\IsblInterpreter\\IsblParser.fsy"
                 : 'Stmt));
# 335 "C:\Projects\IsblInterpreter\IsblInterpreter\IsblParser.fs"
        (fun (parseState : Microsoft.FSharp.Text.Parsing.IParseState) ->
            let _2 = (let data = parseState.GetInput(2) in (Microsoft.FSharp.Core.Operators.unbox data : 'Expr)) in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 39 "C:\Projects\IsblInterpreter\IsblInterpreter\\IsblParser.fsy"
                                                                  Print _2 
                   )
# 39 "C:\Projects\IsblInterpreter\IsblInterpreter\\IsblParser.fsy"
                 : 'Stmt));
# 346 "C:\Projects\IsblInterpreter\IsblInterpreter\IsblParser.fs"
        (fun (parseState : Microsoft.FSharp.Text.Parsing.IParseState) ->
            let _1 = (let data = parseState.GetInput(1) in (Microsoft.FSharp.Core.Operators.unbox data : 'Stmt)) in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 42 "C:\Projects\IsblInterpreter\IsblInterpreter\\IsblParser.fsy"
                                                [_1] 
                   )
# 42 "C:\Projects\IsblInterpreter\IsblInterpreter\\IsblParser.fsy"
                 : 'StmtList));
# 357 "C:\Projects\IsblInterpreter\IsblInterpreter\IsblParser.fs"
        (fun (parseState : Microsoft.FSharp.Text.Parsing.IParseState) ->
            let _1 = (let data = parseState.GetInput(1) in (Microsoft.FSharp.Core.Operators.unbox data : 'StmtList)) in
            let _3 = (let data = parseState.GetInput(3) in (Microsoft.FSharp.Core.Operators.unbox data : 'Stmt)) in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 43 "C:\Projects\IsblInterpreter\IsblInterpreter\\IsblParser.fsy"
                                                _3 :: _1  
                   )
# 43 "C:\Projects\IsblInterpreter\IsblInterpreter\\IsblParser.fsy"
                 : 'StmtList));
|]
# 370 "C:\Projects\IsblInterpreter\IsblInterpreter\IsblParser.fs"
let tables () : Microsoft.FSharp.Text.Parsing.Tables<_> = 
  { reductions= _fsyacc_reductions ();
    endOfInputTag = _fsyacc_endOfInputTag;
    tagOfToken = tagOfToken;
    dataOfToken = _fsyacc_dataOfToken; 
    actionTableElements = _fsyacc_actionTableElements;
    actionTableRowOffsets = _fsyacc_actionTableRowOffsets;
    stateToProdIdxsTableElements = _fsyacc_stateToProdIdxsTableElements;
    stateToProdIdxsTableRowOffsets = _fsyacc_stateToProdIdxsTableRowOffsets;
    reductionSymbolCounts = _fsyacc_reductionSymbolCounts;
    immediateActions = _fsyacc_immediateActions;
    gotos = _fsyacc_gotos;
    sparseGotoTableRowOffsets = _fsyacc_sparseGotoTableRowOffsets;
    tagOfErrorTerminal = _fsyacc_tagOfErrorTerminal;
    parseError = (fun (ctxt:Microsoft.FSharp.Text.Parsing.ParseErrorContext<_>) -> 
                              match parse_error_rich with 
                              | Some f -> f ctxt
                              | None -> parse_error ctxt.Message);
    numTerminals = 21;
    productionToNonTerminalTable = _fsyacc_productionToNonTerminalTable  }
let engine lexer lexbuf startState = (tables ()).Interpret(lexer, lexbuf, startState)
let start lexer lexbuf : prog =
    Microsoft.FSharp.Core.Operators.unbox ((tables ()).Interpret(lexer, lexbuf, 0))
